"""add professional services

Revision ID: 18004ca84cdc
Revises: 4a41f7ae656d
Create Date: 2026-08-16 16:39:49.374459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18004ca84cdc'
down_revision: Union[str, Sequence[str], None] = '4a41f7ae656d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professional_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professional_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['professional_id'], ['professionals.id'], name=op.f('fk_professional_services_professional_id_professionals'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_professional_services_service_id_services'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_professional_services')),
    sa.UniqueConstraint('professional_id', 'service_id', name='uq_professional_service')
    )
    op.create_index(op.f('ix_professional_services_professional_id'), 'professional_services', ['professional_id'], unique=False)
    op.create_index(op.f('ix_professional_services_service_id'), 'professional_services', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_professional_services_service_id'), table_name='professional_services')
    op.drop_index(op.f('ix_professional_services_professional_id'), table_name='professional_services')
    op.drop_table('professional_services')
    # ### end Alembic commands ###
